sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t santos/docker-react-sample -f Dockerfile.dev .

script:
  - docker run -e CI=true santos/docker-react-sample npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "DockerReace-env"
  bucket_name: "arn:aws:s3:::elasticbeanstalk-us-east-1-208437747970"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY